steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install', '--quiet']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'build/cmp.bundle.js', 'gs://s.nitropay.com/cmp.bundle.js']
